services:
  ofelia:
    container_name: ofelia
    image: mcuadros/ofelia:latest
    depends_on:
      etl:
        condition: service_started
    volumes:
      # Crucial: Mounts the Docker socket to allow Ofelia to control containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: daemon --docker
    restart: always

  database:
    container_name: database
    build:
      context: ./Database
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL
        - VITE_REVERB_HOST
        - VITE_REVERB_PORT
        - VITE_REVERB_SCHEME
        - VITE_REVERB_APP_KEY
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - api
      - ws
  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:80"
    environment:
      - SERVER_NAME=:80
    env_file:
      - .env

  etl:
    container_name: ETL
    build:
      context: ./ETL
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./Database/init.sql:/app/init.sql
      - ./Database/procedures.sql:/app/procedures.sql
    command: tail -f /dev/null
    depends_on:
      database:
        condition: service_healthy
        restart: true
    restart: always
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.date-job.schedule: "0 10 0 * * *"
      ofelia.job-exec.date-job.command: "sh -c 'python main.py > /proc/1/fd/1 2>&1'"

  ws:
    container_name: ws
    build:
      context: websocket
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis


  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env

  subscribe:
    container_name: subscribe
    build:
      context: api
      dockerfile: Dockerfile
    command: php artisan redis:subscribe
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
volumes:
  db_data: